### ISSUE TITLE
Make a "release" of the specs

### ISSUE THREAD

**Issue by meejah** [magic-wormhole/magic-wormhole-protocols#13]
In order to merge and publish improvements to the protocol it is desirable to integrate things on "main" that may represent future improvements to the protocol.

Thus, it is important to have releases.

**Comment by meejah** [comment]
The first release should probably be against https://github.com/magic-wormhole/magic-wormhole-protocols/commit/9565dad5da53b88eff5677fb30d0146bdea68b69 (i.e. the latest commit on `main` right now).

**Comment by meejah** [comment]
Are these hosted anywhere already? (I assume the RTD https://magic-wormhole.readthedocs.io/en/latest/ is all coming from the Python implementation repo)

**Comment by piegamesde** [comment]
No, not that I know of. We could publish the docs there, but mid-term I'd like to have them as part of a proper magic-wormhole.io home page. Not sure what to do with magic-wormhole.readthedocs.io though. Maybe host information specific to the Python implementation there only?

**Comment by piegamesde** [comment]
Regarding version numbers: not sure how strictly we want to follow semver. I suggest tagging the initial commit with 1.0 and then the current state 1.0.1, as it only contains clarifications and no new features.

**Comment by meejah** [comment]
Sure. I've been using "calver" usually but that seems right for semver (AFAIK).
