### ISSUE TITLE
What are the restrictions on the codes?

### ISSUE THREAD

**Issue by Jacalz** [magic-wormhole/magic-wormhole-protocols#20]
I have been reading through the protocols and documentation to the best of my ability, trying to find more specific documentation on what limits a code can stay within.

How long can the nameplate be? How many words can the code hold? Is there a limit on the amount of characters inside a word in the code?

Sorry for all the questions, I want my make my regular expression matching a little more strict :)

**Comment by piegamesde** [comment]
Nameplates are currently under-specified. They can be arbitrary, but only numbers between 1 and 1000000 (IIRC) will be used by the rendezvous server implementation. I specified them a bit more in 88a8d4205b98b38e2a456e952fd6f94ab1245bc1 as part of #17, but I could take this into a separate pull request if you are interested in this.

The password may be totally arbitrary. The entire concept of "words" and the format used are a pure client convention.

So in the end, a code is just `${nameplate}-${password}`, where both halves are more or less arbitrary non-empty strings.

**Comment by meejah** [comment]
There is an API on the mailbox server intended for tab-completion, but currently it always uses the PGP wordlist. You can list all allocated nameplates, and the intent is that when multiple wordlists are supported -- e.g. for different languages -- then this will (also) tell you which wordlist each nameplate is using.

**Comment by Jacalz** [comment]
Hmm, that seems to suggest that I can’t really make the checks any stricter. Thanks for the answers.
