### ISSUE TITLE
Bring the community together

### ISSUE THREAD

**Issue by piegamesde** [magic-wormhole/magic-wormhole-protocols#4]
At the moment, there are a few sub-communities gathered around their Wormhole implementation. I'd like to bring them closer together. We need a common communication channel that is not GitHub issues. Point in case, I'm writing this issue and it does not really fit well onto any repository at all.

There is #magic-wormhole on Freenode, but only few people are in there. This may partly be because the channel is not advertised prominently, but is hidden somewhere in the documentation. But a reason may also be that IRC is not really appealing to many people, especially newer devs and non-developers. There is a corresponding Matrix channel that is bridged to the IRC FWIW, if people like that we could promote it more aggressively instead.

So if there is some general interest in this, I'm open to discussing alternatives. I've gone through all repositories I could find and ping all users that seem to be active there for visibility (I apologize if I shouldn't have pinged you):

@warner @psanford @meejah @Jacalz @vu3rdd @copyninja @gnyman @bryanchriswhite

**Comment by meejah** [comment]
I think this is a good idea in general!

I'll try to hang out in the `#magic-wormhole` channel more consistently .. and yeah if it's already bridged to matrix that's a plus (I don't really use matrix though).

Perhaps we could turn `magic-wormhole.io` into more of a "pointers to wormhole-related programs, channels, etc" in the immediate future? (This would be up to @waner though, it's his domain and currently just points at the main github repo).

**Comment by piegamesde** [comment]
Regarding the homepage, I had this idea too! Maybe together with a small blog and a Twitter account or something like that.

Btw you pinged a dead account :p

**Comment by piegamesde** [comment]
Okay so I've contacted the Freenode staff and apparently the dash in the channel name is problematic. Everything up to a dash is called the name space, thus the channel resides in the "magic" name space. Our options thus are (as far as I can tell):

- Rename the channel to #magicwormhole or #magic_wormhole or something like that.
- Rename the channel to #wormhole and use that as name space.
- Move the channel to another IRC server, or chose a different platform altogether.

**Comment by piegamesde** [comment]
Well, that didn't really last long at all 😅. Communities left and right are jumping off Freenode now, switching either to libera.chat or to Matrix. What are your opinions on this?

Personally, I'd be fine with Matrix only, but I know some IRC users. We could make a plumbed Matrix room, i.e. one that is bridged to some IRC channel. But unlike a portal room like what we have right now, the "source of truth" would be on the Matrix side.

**Comment by Jacalz** [comment]
I will personally not join any IRC channels for communication. It feels way to old-school without the modern features that make conversations convenient. I would say either Slack or Discord.

**Comment by Jacalz** [comment]
Though I suspect that Matrix will be more than fine as well.

**Comment by meejah** [comment]
I would rather maintain a presence in libera .. but also it would be good to do "whatever has to happen" to bridge other users in. Hard "no" on Slack.

**Comment by piegamesde** [comment]
A Matrix bridge for Libera is being worked on. There already is a new IRC room (same name, `#magic-wormhole`) on irc.libera.chat. I don't know if we can re-use the current Matrix channel, or if a new room will be needed.

If there is the possibility, I'll try to have the bridge set up in a way such that Matrix is the "source of truth" and not IRC. This seems to be the common way to do it for new rooms.

**Comment by meejah** [comment]
I don't know what the implications of the "source of truth" comments are, but I guess you mean that IRC is "bridged to matrix" instead of the other way around? As long as both IRC and matrix users can chat together, I don't have strong feelings either way.

**Comment by piegamesde** [comment]
Technically, the difference is between portal rooms and plumbed rooms: https://matrix.org/docs/guides/types-of-bridging#types-of-rooms

From a user point of view, the main difference is who manages the access control and the operators/moderators.

**Comment by meejah** [comment]
I'm not very well-versed in either IRC *or* Matrix management of that stuff, so again doesn't matter a lot to me. I'm happy to learn more about Matrix (or IRC ops) as-needed .. but also happy to let you do some of this management if you're keen :)

I am usually idling in IRC and will continue to do so; I don't currently have a workflow for Matrix.

**Comment by vu3rdd** [comment]
I like irc though I am not always active. I had znc setup and I log in occasionally. I don't have matrix setup at the moment. I tried to find an emacs client for matrix and even got it working, but it wasn't as easy as setting up and logging into irc.

I strongly feel Free Software should use free tools and protocols. I don't like to use slack for any free software work. (Even github fwiw, but then we are stuck with it for now and our brain cycles are probably best spent tackling other problems).

But then I use irc very sporadically, so I would just leave that decision to others who use it more actively than I am.

**Comment by piegamesde** [comment]
**For now, the official channels are `#magic-wormhole` on matrix.org and libera.chat, and they are bridged. I hope that this be the final destination on this wild journey.** Unless unexpected things blow up, I'll start updating the documentation and badges to point to them in a few days.

The old Freenode channel has not been migrated to the new Freenode network. It is not registered and nobody has operation rights on it. I'll idle in there telling people where to go for a few days, and then leave this shit behind me.

The old Matrix channel is in an even worse state. It was already kind of desync for a while now, but the Freenode net split totally finished it off. Messages only propagate in only one direction among other things. I will try to get admin rights in there in order to cleanly shut the channel down by setting a tombstone. This will probably take some time.

**Comment by meejah** [comment]
Thanks for the update, and work!

That all sounds good; leaving Freenode behind seems to be the only viable option anyway. Updates to point to the new places sounds great :)
