### ISSUE TITLE
Clickable link format

### ISSUE THREAD

**Issue by k8ieone** [magic-wormhole/magic-wormhole-protocols#42]
So far the most common way I use Magic Wormhole is that I send a code to someone over some kind of chat, mostly Matrix.

Right now the situation is that I use Warp to create a code that I send to someone. That someone then needs to open their Wormhole client, copy the code and paste it into the client.

If Wormhole had a clickable link that would open their client, it would just be a matter of clicking that link. The client would open up and parse the code from the link. It sounds a lot more convenient.

It would be very nice if there was some standardized way to register Wormhole clients to handle a type of URL. I saw #21 and that implemented a standardized URL scheme for this. Currently it's being used in QR codes. However no chat client I've tried sees `wormhole-transfer:1-some-code` as a clickable link, so there's no way to open it.

I'm not exactly sure what the right answer to this is. I've tried sending `wormhole-transfer://1-some-code` and some chat clients do seem to recognize that as an URL, but some don't. Most notably Element and Element X don't. Interestingly enough Warp is already registered to handle this link on my desktop. Although it says the URL is invalid.

Android an iOS both have a concept of applinks which sounds nice for those platforms, but I'm not sure how this could be implemented in things like Warp which is a desktop/mobile Linux app or any other app on any other platform for that matter.

From my understanding applinks are standard http(s) links, but somewhere on the domain where the link leads there is a well-known file which these mobile operating systems download and register a handler for the app that is mentioned in that well-known file. Another issue with this is centralization. From my understanding having an applink registered would tie all clients to one central HTTP server (though used minimally, only for getting that well-known file).

Both platform have slight differences in how it all works. And since afaik there is nothing like this standardized for the desktop, I'm not sure how helpful this is. It would need to be implemented by the Wormhole clients themselves and either based on one of the mobile implementations or they'd have to do it yet another way.

Now that I think about it, this could be something for the likes of freedesktop to standardize. But I guess that would be far off in the future.

This is not an implementation proposal or anything, I'm only looking for this from a user's perspective. Just wanted to spark a potential discussion about this.

**Comment by k8ieone** [comment]
Quick note: I found [Junction](https://apps.gnome.org/Junction/) which is basically an application chooser for links. It shouldn't matter to it if the link is valid. This way a user would be able to choose to open the link in their Wormhole client.

The only requirement would be to have the link recognized by chat apps.

**Comment by meejah** [comment]
I'm not sure how to teach chat clients that `wormhole-transfer:1-foo-bar` is indeed a valid URI format (it is) other than registering it? How are e.g. `mailto:...` links handled by chat clients?

See also https://github.com/magic-wormhole/magic-wormhole-protocols/blob/main/uri-scheme.md (the result of the PR you linked).

**Comment by k8ieone** [comment]
Fractal seems to ignore the `mailto:` part and only highlights the e-mail address as a clickable link, Element X does the same thing.

Element desktop highlights the whole thing.

**Comment by k8ieone** [comment]
Perhaps this would better be targeted at the chat clients' implementations of URI handling?

I don't know how standardized the `something:something-else` is for URIs. Looking at https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Example_URIs, there do seem to be other uses for custom schemes. So it would probably be best if the chat clients would recognize `scheme:path` as well, not only `scheme://path`.

**Comment by meejah** [comment]
The currently-specified URL scheme is definitely intended to be a valid URL (https://url.spec.whatwg.org) and if it is not, please re-open!

Beyond that, I don't know what particular chat clients need to change to properly parse a URL; if there's anything we can do (or write down) to make implementers' lives easier, please re-open :)
